config/routes.rb
Todolist::Application.routes.draw do

  devise_for :users 
  resources :todos, except: [:show]

  root 'welcome#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :description, length: { minimum: 5 }
  default_scope { order('updated_at ASC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController 
  
  before_action :authenticate_user!
  
  def index
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.create(todo_params)
    if @todo.persisted?
      redirect_to todos_path, notice:'Item was saved' 
    else 
      render :action => :new
    end
  end

  def destroy
    @todo = Todo.where(user_id: current_user.id).find(params[:id])
    @todo.destroy
    redirect_to todos_path, notice: 'Todo was deleted' 
  end

  private

  def todo_params
    params.require(:todo).permit(:description) 
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
  def index 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def days_left_to_complete(todo)
    seconds = 7.days - (Time.now - todo.created_at)
    days = (seconds/86400).to_i  
    remaining_seconds = seconds%86400
    hours = (remaining_seconds/3600).to_i 
    return "You have #{days} days and #{hours} hours to complete this task"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div class="container">
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="nav nav-tabs">
  <% if current_user %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
  <% end %>
</div>
     <div class="masthead">
        <h3 class="text-muted">Luis Todo List</h3>
        <nav>
          <ul class="nav nav-justified">
            <li > <%= link_to "Home", root_path %> </li>
            <li> <%= link_to "Todo List", todos_path %></li>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            
          </ul>
        </nav>
     </div>

      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
      </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
<%= yield %>
</div>


</body>

</html>

app/views/todos/index.html.erb
<div class="jumbotron">
<%= link_to "New Todo Item", new_todo_path, class: "btn btn-primary btn-xs btn-block" %>
</div>

<div class="block">
   <% @todos.each do |todo| %>
   <p> <%= todo.description %></p>
   <p class="dim"><%="#{days_left_to_complete(todo)}"%></p>
   <p><%= link_to "Click to complete", { action: "destroy", id: todo.id },
                 method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %></p>

 <footer class="border">
       
      </footer>

    <% end %>
</div>

app/views/todos/new.html.erb
<div class ="block">
<%= form_for @todo do |form| %>
  <div class="form-group">
    <%= form.text_field :description, placeholder: 'Type Todo Item Here'%><br> <br>
    <p>
    <%= form.submit 'save', class: "btn btn-primary" %></p>
  </div>
<% end %>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Welcome to the TodoList application!</h1>
        <p class="lead">The only application on the web that will complete your todo list. Need to do Homework, do laundry, go to the bank and don't have the time?. No problem, just type your Todo item and the application will take care of the rest. Each todo item will automatically be completed after seven days.</p>
        <% if current_user %>
         <p><%= link_to "Get started", todos_path, class: "btn btn-lg btn-success" %> </p>
        <% else %>
         <p><a class="btn btn-lg btn-success" href="/users/sign_up" role="button">Sign up now and find out what everyone is talking about</a></p>
         <p><a class="btn btn-lg btn-primary" href="/users/sign_in" role="button">Already a member click here to sign in</a></p>

        <%end%>
      </div>
      


      <!-- Site footer -->
      <footer class="footer">
        <p>&copy; Created by Luis Menjivar</p>
      </footer>
  </body>
</html>